#!/bin/bash
#
# Copyright 2025 PhysiCar AI
#
# Script to create udev rules for PhysiCar USB devices

echo ""
echo "This script copies a udev rule to /etc to facilitate bringing"
echo "up the PhysiCar USB connection."
echo ""

SCRIPT_DIR="$(ros2 pkg prefix physicar_bringup)/share/physicar_bringup/script"

sudo cp "${SCRIPT_DIR}/99-physicar-cdc.rules" /etc/udev/rules.d/

echo ""
echo "Reload rules"
echo ""
sudo udevadm control --reload-rules
sudo udevadm trigger

echo "Done! PhysiCar udev rules have been installed."
